<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCynkom7\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCynkom7/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCynkom7.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCynkom7\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCynkom7\appProdProjectContainer([
    'container.build_hash' => 'Cynkom7',
    'container.build_id' => '6c7ef997',
    'container.build_time' => 1644672674,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCynkom7');
